global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Xml.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.Playwright;
global using Microsoft.Playwright.MSTest;
global using System.Text.RegularExpressions;
global using UIAutomation_Playwright.Browser;
global using UIAutomation_Playwright.Pages;
global using System.Configuration;
global using AventStack.ExtentReports;
global using AventStack.ExtentReports.Reporter;
global using System.Drawing;
global using System.Threading.Tasks;
global using UIAutomation_Playwright.TestData;
global using BrowserType = Microsoft.Playwright.BrowserType;